name: Deploy Hexo Blog
            
on:
  push:
    branches:
      - master  # 或者你的主分支名称，例如 master
    paths:
      - 'source/_posts/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16 # 或者你需要的 Node.js 版本

    - name: Install Dependencies
      run: npm install

    - name: Build Hexo
      run: npx hexo generate
      
    - name: Start SSH Agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Configure Git User & Deploy Hexo
      env:
        GIT_USER: ${{ secrets.GIT_USER }} # 可选，Git 用户名
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }} # 可选，Git 邮箱
        # 如果你的 hexo-deployer-git 需要其他环境变量，也在这里添加
      if: env.GIT_USER != '' && env.GIT_EMAIL != ''
      run: |
          git config --global user.name "${{ env.GIT_USER }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          run: npx hexo deploy

    
      



